### ISSUE TITLE
Point Cloud doesn't work

### ISSUE THREAD

**Issue by stepanoffweb** [invent-box/Learn-WebGL#2]
I've been trying but don't found a solution for my case: 
Chrome v.78.0.3904.108 , (64 bit) 
The point cloud seems to be a flat circle if I write ```gl.drawArrays(gl.TRIANGLES, 0, vertexData.length / 3);``` instead of ```gl.drawArrays(gl.POINTS, 0, vertexData.length / 3);```
Otherwise, nothing is happening (black screen without error). Some people had the same trouble.

**Comment by andrusha19** [comment]
try adding in your vertex shader main function this code:
gl_PointSize=1.0;

**Comment by DariusMontez** [comment]
Closed by #3
